func_uuid: Add a new dialplan function to generate UUIDs
asterisk/asterisk pull request #1011
Opened 2024-12-01 19:45 UTC by braams

This function is useful for uniquely identifying calls, recordings, and other entities in distributed environments, as well as for generating an argument for the AudioSocket application.

2024-12-01 19:50 UTC, braams commented
cherry-pick-to: 20
cherry-pick-to: 21
cherry-pick-to: 22

2024-12-02 13:45 UTC, jcolp requested changes

2024-12-02 13:45 UTC, jcolp commented on funcs/func_uuid.c
> +	<support_level>core</support_level>
extended

2024-12-03 10:15 UTC, jcolp approved these changes

2024-12-03 18:07 UTC, merged