chan_pjsip:  Add the same details as PJSIPShowContacts to the CLI via 'pjsip show contact'
asterisk/asterisk pull request #1015
Opened 2024-12-02 20:00 UTC by intellasoft

CLI 'pjsip show contact' does not show enough information.
One must telnet to AMI or write a script to ask Asterisk for example what the User-Agent is on a Contact
This feature adds the same details as PJSIPShowContacts to the CLI

Resolves: #643

2024-12-02 20:05 UTC, intellasoft commented
cherry-pick-to: 20
cherry-pick-to: 21
cherry-pick-to: 22

2025-01-16 09:34 UTC, jcolp requested changes

2025-01-16 09:34 UTC, jcolp commented on res/res_pjsip/location.c
> +	/* Detailed view  or one entity start here */
This should use the same functionality as the other CLI commands for printing out the detailed information, ast_sip_cli_print_sorcery_objectset - an example can be seen in the AOR command. This ensures that if Contact is extended with additional fields they will be automatically shown in the CLI command and also gives consistency across the various CLI commands.

2025-02-14 02:34 UTC, asteriskteam commented
This PR has been marked stale because it has been in "Changes Requested" or "submitter-action-required" state for 28 days or more. Please make the requested changes within 14 days or the PR will be closed.

2025-02-28 02:39 UTC, asteriskteam commented
This PR has been closed because it has been in "Changes Requested" or "submitter-action-required" state for more than 42 days.

2025-03-28 08:31 UTC, jcolp approved these changes

2025-03-28 16:27 UTC, merged