Added mime type to format_gsm.c
asterisk/asterisk pull request #1017
Opened 2024-12-03 10:06 UTC by alexey-khabulyak

Because URL parser does not work properly and has been removed(https://github.com/asterisk/asterisk/commit/6428124b06bc0147ce6c6379a96da4c8ac559af7), i added mime type to format_gsm to parse file extensions from content-type:

```
Connected to Asterisk 20.11.0 currently running on asterisk20 (pid = 3316)
asterisk20*CLI> media cache show http://asterisk.khabulyak.su/gsm/your
URI: http://asterisk.khabulyak.su/gsm/your
----------------------------------------
                        Path: /var/cache/asterisk/bucket-TjDHtf.gsm
                        etag: "674dc5f6-420"
               last-modified: Mon, 02 Dec 2024 14:36:38 GMT
                         ext: .gsm
                content-type: audio/x-gsm
            __actual_expires:                     1733152296
```

Without this change asterisk can't determine file extension in this case and can't play a file.

```
    -- Executing [123@main:1] answer("PJSIP/6001-00000003", "")
       > 0x7fa710032300 -- Strict RTP learning after remote address set to: 10.34.134.8:4004
    -- Executing [123@main:1] playback("PJSIP/6001-00000003", "http://asterisk.khabulyak.su/gsm/your")
       > 0x7fa710032300 -- Strict RTP learning after remote address set to: 10.34.134.8:4004
    -- <PJSIP/6001-00000003> Playing 'http://asterisk.khabulyak.su/gsm/your.gsm' (language 'en')
       > 0x7fa710032300 -- Strict RTP switching to RTP target address 10.34.134.8:4004 as source
    -- Auto fallthrough, channel 'PJSIP/6001-00000003' status is 'UNKNOWN'
```

2024-12-03 11:22 UTC, alexey-khabulyak commented
cherry-pick-to: 20
cherry-pick-to: 21
cherry-pick-to: 22

2024-12-03 13:06 UTC, seanbright commented
The URL parser works fine and was not removed.

2024-12-03 13:33 UTC, alexey-khabulyak commented
@seanbright yep, i was wrong. url parser was not removed. content type is checked first now.
but still, `file_extension_from_url_path `sometimes can't get extensions.
for example we have a problem with urls like this:
`https://storage-service.private.dev.domain.com/download?path=prompts/en/silence/0_5.gsm`

or if does not contain file extentions:
`http://asterisk.khabulyak.su/gsm/your`

2024-12-03 15:02 UTC, gtjoseph requested changes
@alexey-khabulyak You need to sign the Contributor License Agreement.  If you did already, can you make sure that the email address in your commit is associated with your github account?
Thanks.

2024-12-03 17:05 UTC, seanbright requested changes
Your commit message needs to be updated according to [the commit message guidelines](https://docs.asterisk.org/Development/Policies-and-Procedures/Commit-Messages).

2024-12-03 17:05 UTC, seanbright commented on formats/format_gsm.c
> +	.mime_types= "audio/gsm|audio/x-gsm",
There should be a space before the `=`.

Also, [`audio/gsm` is a registered mime type](https://www.iana.org/assignments/media-types/audio/GSM), so the `x-gsm` variant should not be necessary here.

2024-12-03 18:29 UTC, seanbright approved these changes

2024-12-04 19:04 UTC, alexey-khabulyak commented
@gtjoseph , i've signed the CLA.

2024-12-04 20:08 UTC, gtjoseph requested changes
If you can wrap your commit message at 78 columns you should be good to go.

2024-12-05 14:40 UTC, alexey-khabulyak commented
> If you can wrap your commit message at 78 columns you should be good to go.

check now, please

2024-12-10 09:38 UTC, jcolp approved these changes

2024-12-10 13:25 UTC, merged