res_pjsip: Add new AOR option "qualify_2xx_only"
asterisk/asterisk pull request #1019
Opened 2024-12-03 16:40 UTC by kdanderso

Added a new option "qualify_2xx_only" to the res_pjsip AOR qualify
feature to mark a contact as available only if an OPTIONS request
returns a 2XX response. If the option is not specified or is false,
any response to the OPTIONS request marks the contact as available.

UserNote: The pjsip.conf AOR section now has a "qualify_2xx_only"
option that can be set so that only 2XX responses to OPTIONS requests
used to qualify a contact will mark the contact as available.

2024-12-03 17:11 UTC, seanbright requested changes
The only question is... how long until someone wants to make this a configurable range of response codes?

2024-12-03 17:29 UTC, gtjoseph submitted a review, later dismissed

2024-12-03 17:29 UTC, gtjoseph commented on res/res_pjsip/location.c
> +	ast_sorcery_object_field_register(sorcery, "contact", "qualify_2xx_only", "no", OPT_YESNO_T, 1, FLDSET(struct ast_sip_contact, qualify_2xx_only));
OPT_BOOL_T to match the alembic script.

2024-12-03 17:29 UTC, gtjoseph commented on res/res_pjsip/location.c
> +	ast_sorcery_object_field_register(sorcery, "aor", "qualify_2xx_only", "no", OPT_YESNO_T, 1, FLDSET(struct ast_sip_aor, qualify_2xx_only));
OPT_BOOL_T to match the alembic script.

2024-12-17 22:52 UTC, mbradeen approved these changes

2024-12-20 09:54 UTC, jcolp approved these changes

2024-12-26 14:58 UTC, merged