sig_analog: Allow immediate fake ring to be suppressed.
asterisk/asterisk pull request #119
Opened 2023-05-25 18:31 UTC by InterLinked1

When immediate=yes on an FXS channel, sig_analog will start fake audible ringback that continues until the channel is answered. Even if it answers immediately, the ringback is still audible for a brief moment.
This can be disruptive and unwanted behavior.

This adds an option to disable this behavior, though the default behavior remains unchanged.

Resolves: #118
ASTERISK-30003
Imported from: https://gerrit.asterisk.org/c/asterisk/+/19715

UserNote: The immediatering option can now be set to no to suppress the fake audible ringback provided
when immediate=yes on FXS channels.

2023-05-26 00:02 UTC, InterLinked1 commented
cherry-pick-to: 20
cherry-pick-to: 18

2023-05-30 08:58 UTC, jcolp submitted a review, later dismissed

2023-06-05 18:31 UTC, gtjoseph requested changes
No merger commits please.
Please squash.

2023-06-05 19:32 UTC, InterLinked1 commented
> No merger commits please. Please squash.

Whoops, I was attempting to fix a merge conflict but I guess that didn't work out.

Rebasing like with Gerrit doesn't seem to get anywhere. Is there a good way of squashing offline? I know the "Squash and merge" on GitHub somehow does it magically but attempts to squash via `git rebase -i HEAD~2` haven't seemed to have made it better.

Alternately, rather than wrestling with this, is it fine if I just submit a new PR (same content, but base branch updated properly first) or will that mess things up?

2023-06-08 22:06 UTC, InterLinked1 commented
> No merger commits please. Please squash.

Sorry for the delay, I basically started over, rebased from master, and then cherry picked in from Gerrit again and that seems to have worked cleanly. Let me know if there's an issue.

2023-06-30 10:38 UTC, InterLinked1 commented
@gtjoseph I'm not sure if you were trying to update something on this PR (I don't see that on other PRs) but I'm now seeing a notice that the branch is out of date, do I need to rebase or is it good as is? Don't want to just click the magic button, as I'm sure that might screw something up again.

2023-06-30 14:06 UTC, gtjoseph commented
> @gtjoseph I'm not sure if you were trying to update something on this PR (I don't see that on other PRs) but I'm now seeing a notice that the branch is out of date, do I need to rebase or is it good as is? Don't want to just click the magic button, as I'm sure that might screw something up again.

"Out of date" is OK.  It just means that something else was merged into "master" since you last updated the PR.  You _can_ rebase off of current master if you want, but it's not necessary.  You should do it locally then force push the PR rather than using the "Update branch" button.

If it ever says "Merge conflict" then something went in that will make your PR fail to merge.  You'll need to locally rebase your PR branch from master, resolve any  conflicts and force push your PR back up again.

2023-06-30 20:29 UTC, InterLinked1 commented
> > @gtjoseph I'm not sure if you were trying to update something on this PR (I don't see that on other PRs) but I'm now seeing a notice that the branch is out of date, do I need to rebase or is it good as is? Don't want to just click the magic button, as I'm sure that might screw something up again.
> 
> "Out of date" is OK. It just means that something else was merged into "master" since you last updated the PR. You _can_ rebase off of current master if you want, but it's not necessary. You should do it locally then force push the PR rather than using the "Update branch" button.
> 
> If it ever says "Merge conflict" then something went in that will make your PR fail to merge. You'll need to locally rebase your PR branch from master, resolve any conflicts and force push your PR back up again.

Okay, thanks for clarifying. Still a little confused, since it says you've requested changes, but I don't see what the branch being out of date would have to do with that otherwise, is there something else I need to do? I addressed the rebase issue, but it sounds like there's another issue?

2023-06-30 20:43 UTC, gtjoseph approved these changes

2023-06-30 20:44 UTC, gtjoseph commented
The only change I requested was the squash.  Not sure why it didn't dismiss automatically when you re-submitted.

2023-07-05 09:16 UTC, jcolp approved these changes

2023-07-10 14:16 UTC, merged