Makefile downloader enable follow redirects
asterisk/asterisk pull request #137
Opened 2023-06-01 00:10 UTC by miguelangel-nubla

Resolves #136

2023-06-01 08:27 UTC, jcolp requested changes

2023-06-01 08:27 UTC, jcolp commented on configure.ac
> +  DOWNLOAD="${WGET} -L"
wget already follows redirects, the -L option just does:

  -L,  --relative                  follow relative links only

So this is for the case where curl is the only thing available.

2023-06-01 12:57 UTC, jcolp requested changes
Please squash things down to a single commit. Additionally please update the commit message according to our standards:

https://wiki.asterisk.org/wiki/display/AST/Commit+Messages

You also need to run "bootstrap.sh" to regenerate the checked in configure script with this change.

If the change is also applicable to other branches you need to comment to cherry pick to them (current supported are 18 and 20):

https://wiki.asterisk.org/wiki/display/AST/Code+Contribution#CodeContribution-CreateaPullRequest

If cherry picking fails (as it can with configure) you would need to create a PR for the branches instead.

2023-06-01 15:28 UTC, seanbright commented
I might just be paranoid, but I can't help but wonder if we shouldn't be changing `wget` to _not_ follow redirects instead?

2023-06-01 15:46 UTC, miguelangel-nubla commented
cherry-pick-to: 20
cherry-pick-to: 18

2023-06-01 16:01 UTC, seanbright commented
Your most recent push did not have the change to `configure`. I ran `./bootstrap.sh` locally with autoconf 2.69 which reduces the number of affected files and I also updated the commit message to try and match our formatting guidelines.

2023-06-01 16:29 UTC, seanbright approved these changes

2023-06-05 13:49 UTC, jcolp approved these changes

2023-06-05 18:36 UTC, gtjoseph approved these changes

2023-06-05 18:37 UTC, merged