res_pjsip_session: Added new function calls to avoid ABI issues.
asterisk/asterisk pull request #153
Opened 2023-06-06 15:58 UTC by bkford

Added two new functions (ast_sip_session_get_dialog and
ast_sip_session_get_pjsip_inv_state) that retrieve the dialog and the
pjsip_inv_state respectively from the pjsip_inv_session on the
ast_sip_session struct. This is due to pjproject adding a new field to
the pjsip_inv_session struct that caused crashes when trying to access
fields that were no longer where they were expected to be if a module
was compiled against a different version of pjproject.

Resolves: #145

2023-06-06 15:59 UTC, bkford commented
cherry-pick-to: 20
cherry-pick-to: 18

2023-06-08 18:23 UTC, jcolp requested changes
See other review

2023-06-09 08:37 UTC, jcolp requested changes
See other review. Which I thought was master, but isn't.

2023-06-09 17:31 UTC, jcolp approved these changes

2023-06-13 17:45 UTC, gtjoseph approved these changes

2023-06-13 17:59 UTC, merged