Adds manager actions to allow move/remove/forward individual messages in a particular mailbox folder. The forward command can be used to copy a message within a mailbox or to another mailbox. Also adds a VoicemailBoxSummarry, required to retrieve message ID's.
asterisk/asterisk pull request #182
Opened 2023-06-29 18:26 UTC by mbradeen

Resolves: #181

UserNote: The following manager actions have been added

VoicemailBoxSummary - Generate message list for a given mailbox

VoicemailRemove - Remove a message from a mailbox folder

VoicemailMove - Move a message from one folder to another within a mailbox

VoicemailForward - Copy a message from one folder in one mailbox
to another folder in another or the same mailbox.

2023-06-29 18:29 UTC, mbradeen commented
cherry-pick-to: 20
cherry-pick-to: 18
cherry-pick-to: certified/18.9

2023-06-30 14:52 UTC, mbradeen commented
Example commands and output:
Get mailbox contents-
```
'VoicemailBoxSummary',
  Context='default',
  Mailbox='1000'
```
```
Response: Success
ActionID: 1
EventList: start
Message: Voicemail box detail will follow

Event : VoicemailBoxDetail -> {'ActionID': '1', 'Folder': 'INBOX', 'CallerID': '"Carrot" <1002>', 'Date': 'Tue Jun 20 03:59:44 PM UTC 2023', 'Duration': '0', 'Flag': '', 'ID': '1687276784-00000001'}
Event : VoicemailBoxDetail -> {'ActionID': '1', 'Folder': 'Old', 'CallerID': '"Carrot" <1002>', 'Date': 'Tue Jun 20 03:59:11 PM UTC 2023', 'Duration': '0', 'Flag': '', 'ID': '1687276751-00000000'}
Event : VoicemailBoxDetail -> {'ActionID': '1', 'Folder': 'Work', 'CallerID': '"Carrot" <1002>', 'Date': 'Tue Jun 20 04:00:03 PM UTC 2023', 'Duration': '0', 'Flag': '', 'ID': '1687276803-00000002'}
Event : VoicemailBoxDetailComplete -> {'ActionID': '1', 'EventList': 'Complete', 'ListItems': '1'}
```
Move a message from 'Urgent' to 'Inbox'
```
'VoicemailMove',
  Context='default',
  Mailbox='1000',
  Folder='Urgent',
  ID='1687276784-00000011',
  ToFolder='INBOX'
```
```
Response: Success
ActionID: 1
Message: Message move successful

Event : MessageWaiting -> {'Privilege': 'call,all', 'SequenceNumber': '12', 'File': 'manager_mwi.c', 'Line': '136', 'Func': 'mwi_update_cb', 'Mailbox': '1000@default', 'Waiting': '1', 'New': '1', 'Old': '1'}
```

2023-07-05 09:29 UTC, jcolp requested changes

2023-07-05 09:29 UTC, jcolp commented on apps/app_voicemail.c
> +	if((s == NULL) || (vmu == NULL) || (event_name == NULL) || (actionid == NULL)) {
This doesn't conform to our coding guidelines

2023-07-05 09:29 UTC, jcolp commented on apps/app_voicemail.c
> +		ast_log(LOG_ERROR, "Wrong input parameter.");
This is not useful as an error message within the content of this work

2023-07-05 09:29 UTC, jcolp commented on apps/app_voicemail.c
> +	if ((mailbox_snapshot = ast_vm_mailbox_snapshot_create(vmu->mailbox, vmu->context, NULL, 0, AST_VM_SNAPSHOT_SORT_BY_ID, 0))) {
Reduce indentation by returning -1 early if no mailbox snapshot

2023-07-05 09:29 UTC, jcolp commented on apps/app_voicemail.c
> +
This should enforce any required headers so the AMI user gets a more detailed response

2023-07-05 09:29 UTC, jcolp commented on apps/app_voicemail.c
> +
This should enforce any required headers so the AMI user gets a more detailed response

2023-07-05 09:29 UTC, jcolp commented on apps/app_voicemail.c
> +
This should enforce any required headers so the AMI user gets a more detailed response

2023-07-11 13:47 UTC, jcolp requested changes

2023-07-11 13:47 UTC, jcolp commented on apps/app_voicemail.c
> +		ast_log(LOG_ERROR, "Could not append voicemail box info.");
This doesn't contain enough information to be useful, such as the mailbox and context

2023-07-11 13:47 UTC, jcolp commented on apps/app_voicemail.c
> +	if(nummessages < 0) {
if (nummessages < 0) {

2023-07-11 13:47 UTC, jcolp commented on apps/app_voicemail.c
> +		nummessages = 0;
If this fails part way through, what will the result be? Some details sent, but a total messages count of 0?

2023-07-12 08:39 UTC, jcolp approved these changes

2023-07-12 17:26 UTC, gtjoseph approved these changes

2023-07-12 17:37 UTC, merged