sig_analog: Allow three-way flash to time out to silence.
asterisk/asterisk pull request #206
Opened 2023-07-10 18:56 UTC by InterLinked1

sig_analog allows users to flash and use the three-way dial tone as a primitive hold function, simply by never timing it out.

Some systems allow this dial tone to time out to silence, so the user is not annoyed by a persistent dial tone. This option allows the dial tone to time out normally to silence.

Resolves: #205
ASTERISK-30004 #close
Imported from Gerrit: https://gerrit.asterisk.org/c/asterisk/+/19716

UserNote: The threewaysilenthold option now allows the three-way dial tone to time out to silence, rather than continuing forever.

2023-07-10 18:56 UTC, InterLinked1 commented
cherry-pick-to: 20
cherry-pick-to: 18

2023-07-11 13:43 UTC, jcolp approved these changes

2023-07-12 13:48 UTC, gtjoseph requested changes
Per https://docs.asterisk.org/latest/Development/Policies-and-Procedures/Commit-Messages/  Please do NOT intersperse unsupported commit message trailers among the supported ones.  The "ASTERISK-30004..." line MUST come before the standard Resolves, Usernote and UpgradeNote trailers.

2023-07-12 20:25 UTC, InterLinked1 commented
> Per https://docs.asterisk.org/latest/Development/Policies-and-Procedures/Commit-Messages/ Please do NOT intersperse unsupported commit message trailers among the supported ones. The "ASTERISK-30004..." line MUST come before the standard Resolves, Usernote and UpgradeNote trailers.

https://docs.asterisk.org/latest/Development/Policies-and-Procedures/Commit-Messages/ is a 404, but should be fixed now!

2023-07-21 17:54 UTC, InterLinked1 commented
@gtjoseph By the way, I think the same thing has happened here: for some reason, GitHub isn't discussing the stale feedback for an addressed issue, so I'm assuming this probably isn't showing up in the "needs attention queue" or however it works (since it says "Changes requested" which is wrong). But it only seems to happen sometimes, not all the time, trying to see what that might be. Could be my fault since I acknowledged it, maybe I shouldn't be doing that.

2023-07-21 17:56 UTC, gtjoseph commented
Ok. I'll re-review in a bit.

2023-08-04 10:46 UTC, gtjoseph approved these changes

2023-08-04 14:31 UTC, merged