extensions.conf.sample: Remove reference to missing context.
asterisk/asterisk pull request #214
Opened 2023-07-16 15:51 UTC by seanbright

c3ff4648 removed the [iaxtel700] context but neglected to remove references to it.

2023-07-16 15:51 UTC, seanbright commented
cherry-pick-to: 20
cherry-pick-to: 18

2023-07-16 15:58 UTC, InterLinked1 approved these changes

2023-07-17 19:10 UTC, InterLinked1 approved these changes

2023-07-18 16:25 UTC, gtjoseph requested changes
The cherry-picks failed to apply.  I think you're gonna need to separate them.  Maybe one for master and another for 18 and 20?

2023-07-21 17:40 UTC, gtjoseph approved these changes

2023-07-21 17:49 UTC, merged