res_pjsip.c: Add the contact_user to the Contact header
asterisk/asterisk pull request #232
Opened 2023-08-08 14:25 UTC by MikeNaso

If the contact_user in declared in the endpoint it will be inserted in the message

Resolves: #226

2023-08-08 14:29 UTC, MikeNaso commented
cherry-pick-to: 16
cherry-pick-to: 18
cherry-pick-to: 20

2023-08-09 11:57 UTC, MikeNaso commented
> The commit message is not clear or explicit enough. It should state that this extends the contact_user setting for incoming calls while it already worked on outgoing calls.

Done

2023-08-09 13:22 UTC, MikeNaso commented
Now the test failed changing the commit description, very strange

2023-08-09 13:37 UTC, jcolp requested changes
The first line is still not detailed enough. I think the following would be descriptive enough:

    res_pjsip.c: Set contact_user on incoming call local Contact header
    
    If the contact_user is configured on the endpoint it will now be
    set on the local Contact header URI for incoming calls. The
    contact_user has already been set on the local Contact header
    URI for outgoing calls.

2023-08-09 20:56 UTC, MikeNaso commented
Done

2023-08-11 14:44 UTC, jcolp approved these changes

2023-08-14 17:21 UTC, merged