logger: Add channel-based filtering.
asterisk/asterisk pull request #243
Opened 2023-08-09 22:14 UTC by InterLinked1

This adds the ability to filter console
logging by channel or groups of channels.
This can be useful on busy systems where
an administrator would like to analyze certain
calls in detail. A dialplan application is also
included for the purpose of assigning a channel
to a group (e.g. by tenant, or some other metric).

ASTERISK-30483 #close

Imported from Gerrit: https://gerrit.asterisk.org/c/asterisk/+/20029

Resolves: #242

UserNote: The console log can now be filtered by
channels or groups of channels, using the
logger filter CLI commands.

2023-08-09 22:15 UTC, InterLinked1 commented
cherry-pick-to: 18
cherry-pick-to: 20
cherry-pick-to: 21

2023-08-16 23:10 UTC, salahalgamdi707 approved these changes

2023-11-07 11:14 UTC, jcolp requested changes

2023-11-07 11:14 UTC, jcolp commented on main/logger.c
> +	<application name="SetChannelLogGroup" language="en_US">
I don't think this should be a dialplan application. It should be a dialplan function to set and get, which allows it to be set in a PJSIP endpoint definition for example, or when originated in AMI.

2023-11-08 13:27 UTC, jcolp approved these changes

2023-11-09 12:35 UTC, merged