Revert "app_stack: Print proper exit location for PBXless channels."
asterisk/asterisk pull request #254
Opened 2023-08-10 17:23 UTC by creslin287

This reverts commit 617dad4cba1513dddce87b8e95a61415fb587cf1.

apps/app_stack.c: Revert buggy gosub patch

This seems to break the case when a predial macro calls a gosub.
When the gosub calls return, the Return function outputs:

app_stack.c:423 return_exec: Return without Gosub: stack is empty

This returns -1 to the calling macro, which returns to app_dial
and causes the call to hangup instead of proceeding with the macro
that invoked the gosub.

Resolves: #253

2023-08-10 17:30 UTC, creslin287 commented
cherry-pick-to: 20
cherry-pick-to: 18

2023-08-10 17:45 UTC, seanbright approved these changes

2023-08-10 18:27 UTC, creslin287 commented
> Given that you didn't cherry pick to 21, is this not applicable to master since it only affects macros? If this is only happening with macros I don't think this is applicable to master.

Hey!  I can cherry pick to 21 as well. To be honest, I didn't dig deep enough into the patch to figure out what was going on enough to feel that there wouldn't be any other unintended behavioral consequences that I hadn't caught, perhaps in gosub usage. It just seemed safer to do a consistent across all applied branches (and keeps the branches more consistent).

I'd forgotten about 21 though, I can add the cherry pick there as well.

I guess taking a step back though, @jcolp, @gtjoseph, @bkford, and others - what are your thoughts?  Should I leave the patch in master and 21 and revert only for 20 and 18 or should I just revert across the board?

2023-08-10 18:32 UTC, InterLinked1 commented
> > Given that you didn't cherry pick to 21, is this not applicable to master since it only affects macros? If this is only happening with macros I don't think this is applicable to master.
> 
> Hey! I can cherry pick to 21 as well. To be honest, I didn't dig deep enough into the patch to figure out what was going on enough to feel that there wouldn't be any other unintended behavioral consequences that I hadn't caught, perhaps in gosub usage. It just seemed safer to do a consistent across all applied branches (and keeps the branches more consistent).
> 
> I'd forgotten about 21 though, I can add the cherry pick there as well.
> 
> I guess taking a step back though, @jcolp, @gtjoseph, @bkford, and others - what are your thoughts? Should I leave the patch in master and 21 and revert only for 20 and 18 or should I just revert across the board?

You said it only happens with macros. Macros don't exist in 21 or master anymore, that's why I asked, it might not be capable of causing any issues there, and then the fix needs to be readded again if there isn't an issue.

I don't immediately see what the issue here would be with macros, but I never used them myself so I'm not familiar with that code, just that they can cause problems elsewhere so wondering if that's what happened here.

Do you have a POC snippet handy that causes this, that I could use to do some further testing?

2023-08-10 20:36 UTC, InterLinked1 commented
@creslin287 I'm able to reproduce your issue and understand the root cause. Inside a macro, the channel has no PBX, so it's triggering the modification logic.

A simple fix is to not do that if the channel is executing a macro, because macros cause some different behavior. A simple diff:

```
- if (ast_channel_pbx(chan) || !lastframe) {
+ if (ast_channel_pbx(chan) || !lastframe || ast_channel_macrocontext(chan)) {
```

Still, this change does not apply to 21 or master, only 18 and 20, as this symbol isn't even available there.

2023-08-11 13:20 UTC, gtjoseph requested changes
So if this doesn't apply to 21 or master then I think the PR needs to be resubmitted against the 20 branch with a cherry-pick to 18, yes?

2023-08-11 13:32 UTC, InterLinked1 commented
> So if this doesn't apply to 21 or master then I think the PR needs to be resubmitted against the 20 branch with a cherry-pick to 18, yes?

I would think so, yes.
I can submit a patch as proposed above which fixes the issue here without undoing the previous bug fix.

2023-08-11 14:31 UTC, seanbright commented
We should merge this PR. Any subsequent changes to this will need changes to the testsuite to confirm we are not introducing bugs like this.

2023-08-11 14:46 UTC, jcolp commented
I agree. A way to ensure there is test coverage under 21/master should also occur.

2023-08-11 14:47 UTC, jcolp approved these changes

2023-08-15 14:56 UTC, creslin287 commented
Hey, what is left as far as this PR goes?  I saw that George requested changes.  Is the consensus that I should apply the revert to only the 18 and 20 branches and @InterLinked1 will submit a follow up patch, or is it revert across the branches and @InterLinked1 will attempt a version 2 at some point with tests?

2023-08-15 15:16 UTC, InterLinked1 commented
> Hey, what is left as far as this PR goes? I saw that George requested changes. Is the consensus that I should apply the revert to only the 18 and 20 branches and @InterLinked1 will submit a follow up patch, or is it revert across the branches and @InterLinked1 will attempt a version 2 at some point with tests?

I think the plan is to let your revert go through as is for all branches at this moment, and I will follow-up later to re-fix the original bug (so I think you're good). But I think George has to change his review to reflect that... GitHub PRs seem to get "stuck" otherwise and won't show up so might need @gtjoseph 's attention.

2023-08-15 15:23 UTC, gtjoseph approved these changes

2023-08-15 15:24 UTC, gtjoseph commented
Yeah, I got distracted, sorry.  Cherry-pick testing in progress, then I'll merge.

2023-08-16 14:45 UTC, merged