res_pjsip_session: Send Session Interval too small response
asterisk/asterisk pull request #279
Opened 2023-08-28 07:35 UTC by btriller

Handle session interval lower than endpoint's configured minimum timer when sending first answer. Timer setting is checked during this step and needs to handled appropriately.

2023-08-28 07:35 UTC, btriller commented
cherry-pick-to: 18
cherry-pick-to: 20
cherry-pick-to: 21

2023-08-30 10:37 UTC, jcolp requested changes
I think the commit message should be updated to include what previously happened, and what now happens, from a SIP response perspective in this scenario.

2023-08-30 10:37 UTC, jcolp commented on res/res_pjsip_session.c
> +		if (tdata == NULL) {
This needs to be updated according to [coding guidelines](https://docs.asterisk.org/Development/Policies-and-Procedures/Historical-Policies-and-Procedures/Code-Review/Coding-Guidelines/).

if (!tdata) {
} else {
}

2023-08-30 13:09 UTC, jcolp commented on res/res_pjsip_session.c
> +		if (tdata == NULL) {
if (!tdata) {

2023-08-30 13:13 UTC, jcolp approved these changes

2023-08-31 14:22 UTC, merged