app_dial: Fix infinite loop when sending digits.
asterisk/asterisk pull request #282
Opened 2023-08-28 17:53 UTC by InterLinked1

If the called party hangs up while digits are being sent, -1 is returned to indicate so, but app_dial
was not checking the return value, resulting in
the hangup being lost and looping forever until
the caller manually hangs up the channel. We now
abort if digit sending fails.

ASTERISK-29428 #close

Resolves: #281

2023-08-28 17:56 UTC, InterLinked1 commented
cherry-pick-to: 18
cherry-pick-to: 20
cherry-pick-to: 21

2023-08-30 10:35 UTC, jcolp requested changes

2023-08-30 10:35 UTC, jcolp commented on apps/app_dial.c
> +							ast_log(LOG_WARNING, "Called party hung up post-progress before all digits could be sent\n");
This should include channel name

2023-08-30 10:35 UTC, jcolp commented on apps/app_dial.c
> +							ast_log(LOG_WARNING, "Called party hung up post-wink before all digits could be sent\n");
Same here

2023-08-30 10:42 UTC, jcolp approved these changes

2023-08-31 13:20 UTC, merged