chan_iax2: Improve authentication debugging.
asterisk/asterisk pull request #287
Opened 2023-08-30 13:13 UTC by InterLinked1

Improves and adds some logging to make it easier
for users to debug authentication issues.

Resolves: #286

2023-08-30 13:13 UTC, InterLinked1 commented
cherry-pick-to: 18
cherry-pick-to: 20
cherry-pick-to: 21

2023-08-30 19:11 UTC, seanbright requested changes

2023-09-07 18:27 UTC, seanbright approved these changes

2023-09-11 12:36 UTC, jcolp approved these changes

2023-09-20 15:38 UTC, merged