res_rtp_asterisk: fix wrong counter management in ioqueue objects
asterisk/asterisk pull request #302
Opened 2023-09-05 14:26 UTC by vnovy

In function  rtp_ioqueue_thread_remove counter in ioqueue object is not decreased
which prevents unused ICE TURN threads from being removed.

Resolves: #301

cherry-pick-to: 20
cherry-pick-to: 18

2023-09-05 16:46 UTC, vnovy commented
cherry-pick-to: 21
cherry-pick-to: 20
cherry-pick-to: 18

2023-09-07 18:26 UTC, seanbright approved these changes

2023-09-08 12:31 UTC, gtjoseph requested changes
Please remove the cherry-pick lines from the commit message.

2023-09-08 12:37 UTC, vnovy commented
> Please remove the cherry-pick lines from the commit message.

It cannot be fixed in those branches?

2023-09-08 12:46 UTC, vnovy commented
cherry-pick lines removed from the commit message

2023-09-08 12:53 UTC, gtjoseph commented
> 

They can.  It's just that those lines in the commit message can confuse the automation.  They should only be in ONE PR comment.

2023-09-08 12:54 UTC, gtjoseph approved these changes

2023-09-19 08:29 UTC, vnovy commented
Are the failed tests here something real?

2023-09-19 08:32 UTC, jcolp commented
No.

2023-09-19 08:40 UTC, vnovy commented
Thanks. And what can I do to move it forward?

2023-09-19 08:42 UTC, jcolp commented
There is nothing currently pending your involvement.

2023-09-20 15:03 UTC, merged