res_speech: allow speech to translate input channel
asterisk/asterisk pull request #305
Opened 2023-09-07 17:29 UTC by mbradeen

* Allow res_speech to translate the input channel if the
  format is translatable to a format suppored by the
  speech provider.

* Fixed issue in res_speech_aeap when unable to provide an
  input format to check against.

Resolves: #129

UserNote: res_speech now supports translation of an input channel
to a format supported by the speech provider, provided a translation
path is available between the source format and provider capabilites.

2023-09-07 17:30 UTC, mbradeen commented
cherry-pick-to: 21
cherry-pick-to: 20
cherry-pick-to: 18
cherry-pick-to: certified/18.9

2023-09-07 17:32 UTC, jcolp requested changes

2023-09-07 17:32 UTC, jcolp commented on res/res_speech.c
> +			if(ast_translator_best_choice(engine->formats, (struct ast_format_cap *)cap, &best, &best_translated)) {
if (

2023-09-07 17:49 UTC, jcolp submitted a review, later dismissed

2023-09-08 13:51 UTC, gtjoseph requested changes

2023-09-08 13:51 UTC, gtjoseph commented on res/res_speech_aeap.c
res_speech_aeap doesn't exist in certified. I'd remove the update to res_speech_aeap since it's just an error message and put that in a separate PR for 18,20 and 21.

2023-09-11 12:34 UTC, jcolp requested changes

2023-09-11 12:34 UTC, jcolp commented on res/res_speech.c
> +			 * speech_background will translate the channel via ast_set_read_format to this
Don't reference the dialplan app, just state that the consumer of the API is responsible for translating to the chosen format.

2023-09-13 13:54 UTC, jcolp approved these changes

2023-10-27 15:00 UTC, gtjoseph approved these changes

2023-10-30 11:52 UTC, merged