res_pjsip: Expanding pj_sip endpoint ID and relevant resource length to 255 characters
asterisk/asterisk pull request #364
Opened 2023-10-03 17:14 UTC by pchero

res_pjsip: Expanding pj_sip endpoint ID and relevant resource length to 255 characters

This commit introduces an extension to the endpoint and relevant resource sizes for pj_sip, transitioning from its current 40-character constraint to a more versatile 255-character capacity. This enhancement significantly overcomes limitations related to domain qualification and practical usage, ultimately delivering improved functionality. Furthermore, it encompasses adjustments to the realtime database schema and ARI message length to seamlessly accommodate the expanded realm size.

Resolves: #345

2023-10-03 19:27 UTC, InterLinked1 requested changes

2023-10-04 04:58 UTC, pchero commented on contrib/ast-db-manage/config/versions/dac2b4c328b8_incease_pjsip_id_length.py
> +"""incease pjsip id length
Thanks, I fixed it.

2023-10-09 08:46 UTC, jcolp commented
We refer to PJSIP as "PJSIP" not "pj_sip". I also don't understand the portion of the commit message regarding ARI. It's not adjusting the ARI message length, it's adjusting the maximum realm length for it as well.

2023-10-11 11:58 UTC, pchero commented
> We refer to PJSIP as "PJSIP" not "pj_sip". I also don't understand the portion of the commit message regarding ARI. It's not adjusting the ARI message length, it's adjusting the maximum realm length for it as well.

Ah, thanks. I fixed the commit message. And because it extends the max length of the realm - which ARI affected changes,  I mentioned it.
https://github.com/asterisk/asterisk/pull/364/files#diff-b955bcdc2839febf4889973ab5db734dcd163169f7ce0b233be0379311912683L62

2023-10-14 01:33 UTC, pchero commented
> At least 1 approving review is required to merge this pull request. Still in progress?

Yes, the PR is ready. Feel free to review anyone. :)

2023-10-16 08:58 UTC, jcolp approved these changes

2023-10-16 15:11 UTC, mbradeen approved these changes

2023-10-17 13:46 UTC, gtjoseph requested changes
I think this needs a UserNote letting people know that they can set the realm to > 40 characters now.
I think this also needs an UpgradeNote letting people know that the realtime max length for all ids has been changed from 40 to 255 and that if they want to take advantage of that, they need to run alembic to upgrade their schemas.

2023-10-17 17:37 UTC, pchero commented
Hi @gtjoseph, I updated the commit message. Could you please check it out? Thanks in advance.

2023-10-19 13:46 UTC, gtjoseph approved these changes

2023-10-19 14:40 UTC, jcolp approved these changes

2023-10-20 01:21 UTC, pchero commented
Hi team,
Looks like some tests failed. But I'm not clear what to do.
If there's something that has to be done by my side, please let me know.

2023-10-20 12:06 UTC, gtjoseph commented
> Hi team, Looks like some tests failed. But I'm not clear what to do. If there's something that has to be done by my side, please let me know.

They're known failures.  Everything seems OK.

2023-10-20 12:19 UTC, merged