res_curl: Add convenience functions for curl.
asterisk/asterisk pull request #374
Opened 2023-10-11 21:08 UTC by gtjoseph

There are new functions available in res_curl that mame
using curl much easier.  See the documentation in res_curl.h
for more information.

At some point, the functions in func_curl that are not specifically
involved with providing a dialplan interface should be refactored
to use the the new functions in res_curl as should any other
modules that called func_curl as a convenience.

2023-10-11 21:08 UTC, gtjoseph commented
cherry-pick-to: 18
cherry-pick-to: 20
cherry-pick-to: 21
cherry-pick-to: certified/18.9

2023-10-11 21:12 UTC, seanbright commented
This seems not that useful to me

2023-10-11 21:27 UTC, InterLinked1 requested changes
mame is misspelled in the commit message

2023-10-11 21:27 UTC, InterLinked1 commented on include/asterisk/res_curl.h
> +\section Overwiew Overview
Overview

2023-10-12 12:55 UTC, seanbright requested changes
There should be two functions defined (not that neither has `curl` in their name):

* `ast_url_download_to_string(...)`
* `ast_url_download_to_file(...)`

If you need additional complexity you can just use the curl API. This additional abstraction does not make sense.

2023-10-12 13:15 UTC, jcolp commented
I agree with @seanbright, it seems unnecessary to make a generic method like this.

2023-10-12 13:26 UTC, gtjoseph commented
Here's the code in stir/shaken now:
```
	struct ast_curl_header_data header_data = {
		.debug_info = cert->public_url,
		.headers = NULL,
	};
	struct ast_curl_write_data write_data = {
		.max_download_bytes = 8192,
		.debug_info = cert->public_url,
		.stream_buffer = NULL,
	};
	struct ast_curl_open_socket_data socket_data = {
		.acl = cert->acl,
		.debug_info = cert->public_url,
	};
	struct ast_curl_optional_data optional_data = {
		.curl_open_socket_cb = ast_curl_open_socket_default_cb,
		.curl_open_socket_data = &socket_data
	};

	http_code = ast_curler(cert->public_url, ss_vs_get_curl_timeout(),
		ast_curl_write_default_cb, &write_data, ast_curl_header_default_cb,
		&header_data, &optional_data);
```

You guys think I should scrap the res_curl stuff and pull it back to stir/shaken?

2023-10-12 13:32 UTC, jcolp commented
Yes.

2023-10-12 13:34 UTC, closed without merging