Feature: add access to Reason headers via HANGUPCAUSE()
asterisk/asterisk pull request #404
Opened 2023-10-31 13:50 UTC by IgorrG

This merge request in most duplicate idea of https://github.com/asterisk/asterisk/pull/113, but use other idea behind of implementation. As soon as SIP call may be end with several Reason headers, we want to make all of them available through the HAGUPCAUSE() function. 

This implementation use same ao2 hash for cause codes storage and add a flag to make difference between last processed sip message and content of reason headers.

2023-10-31 13:58 UTC, InterLinked1 requested changes
The two commits need to be squashed

2023-10-31 13:58 UTC, InterLinked1 commented on funcs/func_hangupcause.c
> +	struct ast_str *causelist = ast_str_create(128);
This looks like mixed declarations and statements

2023-10-31 13:58 UTC, InterLinked1 commented on include/asterisk/channel.h
> + * \since 22
I don't think \since 22 is correct here, someone else may have further comments on this

2023-10-31 13:58 UTC, InterLinked1 commented on include/asterisk/frame.h
> +	unsigned int cause_extended:1;		/*!< Indicates whether this cause code retrieved from supplimentary sources */
supplementary

was retrieved?

2023-10-31 13:58 UTC, InterLinked1 commented on main/channel_internal_api.c
> +	return (!strcmp(pc_str, str)) ? CMP_MATCH | CMP_STOP : 0;
Adding parentheses here is superfluous and irrelevant to this change.

2023-10-31 14:51 UTC, gtjoseph requested changes
Please address @InterLinked1's comments

2024-03-20 19:36 UTC, asteriskteam commented
This PR has been marked stale because it has been in "Changes Requested" or "submitter-action-required" state for 28 days or more. Please make the requested changes within 14 days or the PR will be closed.

2024-04-04 02:04 UTC, asteriskteam commented
This PR has been closed because it has been in "Changes Requested" or "submitter-action-required" state for more than 42 days.

2024-04-04 02:04 UTC, closed without merging