chan_iax2: Add log message for rejected calls.
asterisk/asterisk pull request #414
Opened 2023-11-06 12:59 UTC by InterLinked1

Certain calls can fail due to networking/DNS misconfigurations where a call is made to a loopback address on which chan_iax2 is not listening. When this happens, there is no relevant logging currently, making this very difficult to track down. This issue can be detected reliably, so this adds a warning message to direct users to check their configuration.

Resolves: #413

2023-11-06 13:14 UTC, seanbright commented
“Possible network issue?” 

How is this useful?

2023-11-06 13:26 UTC, InterLinked1 commented
> “Possible network issue?”
> 
> How is this useful?

It's something to go off of, and there are more comments in the code that can be used if needed.
I didn't want to get too specific like "Check /etc/hosts for non-canonical loopback addresses" because it's not guaranteed that the issue is there, that's why I tried to keep it generic.

2023-11-06 13:50 UTC, InterLinked1 commented
> This is why I suggested actually digging in more to truly understand the scenario and what is going on to provide a better and more helpful message in the correct situation.

If chan_iax2 isn't listening on the particular loopback address, the packets are being sent somewhere and not actually getting processed, hence the lack of a valid call number at this point. Why it is that someone is trying to dial a loopback address that isn't being listened on is really their issue to resolve, but this should clue them in on that hopefully.

2023-11-06 13:54 UTC, jcolp commented
On further looking, they were actually being received so my initial analysis was incorrect - why things went awry I don't know, but it was seemingly due to not explicitly binding. I don't think it's actually understood why it's doing what it is doing, beyond that binding explicitly causes it to work.

2024-12-02 13:47 UTC, seanbright requested changes
This should not be marked as fixing the associated issue. That issue should remain open.

2024-12-02 15:28 UTC, seanbright approved these changes

2024-12-02 19:52 UTC, gtjoseph commented
@InterLinked1 Cherry-pick?

2024-12-02 21:32 UTC, InterLinked1 commented
cherry-pick-to: 20
cherry-pick-to: 21
cherry-pick-to: 22

2024-12-03 14:36 UTC, merged