general: Fix broken links.
asterisk/asterisk pull request #431
Opened 2023-11-09 21:28 UTC by InterLinked1

This fixes a number of broken links throughout the tree, mostly caused by wiki.asterisk.org being replaced with docs.asterisk.org, which should eliminate the need for sporadic fixes as in f28047db36a70e81fe373a3d19132c43adf3f74b.

Resolves: #430

2023-11-09 21:28 UTC, InterLinked1 commented
cherry-pick-to: 18
cherry-pick-to: 20
cherry-pick-to: 21

2023-11-09 22:36 UTC, seanbright requested changes

2023-11-09 22:36 UTC, seanbright commented on README.md
> +[wiki]: https://docs.asterisk.org/
It's not a wiki

2023-11-09 22:36 UTC, seanbright commented on configs/samples/pjsip.conf.sample
> -; for more information.
Don't delete without a replacement

2023-11-09 22:36 UTC, seanbright commented on configs/samples/res_snmp.conf.sample
> -; snmp support in Asterisk
Don't delete

2023-11-09 22:36 UTC, seanbright commented on configs/samples/sla.conf.sample
> +; See https://docs.asterisk.org or doc/AST.pdf for more information.
Pretty sure we don't generate `AST.pdf` anymore so you can remove the mention of it

2023-11-09 22:36 UTC, seanbright commented on doc/README.txt
>  project wiki:
Not a wiki

2023-11-09 22:36 UTC, seanbright commented on doc/asterisk.8
> +https://docs.asterisk.org - The Asterisk Wiki
Not a wiki

2023-11-09 22:36 UTC, seanbright commented on doc/asterisk.sgml
> +   https://docs.asterisk.org/ - The Asterisk Wiki
Not a wiki

2023-11-09 22:36 UTC, seanbright commented on main/asterisk.c
> + * \li https://docs.asterisk.org Asterisk Wiki
Not a wiki

2023-11-09 22:36 UTC, seanbright commented on main/stasis.c
>   * reference message types. This is fully detailed on the wiki at
Not a wiki

2023-11-09 22:36 UTC, seanbright commented on res/res_pjsip/pjsip_config.xml
> +						the Asterisk wiki https://docs.asterisk.org/Configuration/Channel-Drivers/SIP/Concepts/SIP-Direct-Media-Reinvite-Glare-Avoidance/
Not a wiki

2023-11-28 11:17 UTC, jcolp requested changes

2023-11-28 11:17 UTC, jcolp commented on configs/samples/pjsip.conf.sample
>  ; See https://wiki.asterisk.org/wiki/pages/viewpage.action?pageId=30278158
This is https://docs.asterisk.org/Configuration/Channel-Drivers/SIP/Configuring-res_pjsip/Resource-List-Subscriptions-RLS/

2023-11-28 13:26 UTC, jcolp approved these changes

2023-12-08 13:11 UTC, merged