app_voicemail_odbc: remove macrocontext from voicemail_messages table
asterisk/asterisk pull request #528
Opened 2024-01-10 16:49 UTC by mbradeen

When app_macro was removed, the macrocontext column was left and skipped
when inserting - breaking app_voicemail_odbc. This change removes the
macrocontext column via alembic and re-numbers the existing columns.

Fixes: #527

UserNote: The fix requires that the voicemail database be upgraded via
alembic

UpgradeNote: Upgrading to the latest voicemail database via alembic will
remove the macrocontext column from the voicemail_messages table.

2024-01-10 16:49 UTC, mbradeen commented
cherry-pick-to: 21

2024-01-10 16:50 UTC, jcolp approved these changes

2024-01-15 13:55 UTC, gtjoseph requested changes
I had to go look at the code to understand what happened.  This might be a better commit description: 

When app_macro was deprecated, the macrocontext column was removed from the INSERT statement and while the macrocontext parameter bind was removed, the binds weren't renumbered.  This broke the insert.

Also, I think the UserNote content should be the first sentence of the UpgradeNote.

2024-01-15 15:59 UTC, jcolp approved these changes

2024-01-17 13:28 UTC, gtjoseph approved these changes

2024-01-17 15:01 UTC, merged