utils: Make behavior of ast_strsep* match strsep.
asterisk/asterisk pull request #568
Opened 2024-01-31 14:05 UTC by jcolp

Given the scenario of passing an empty string to the ast_strsep functions the functions would return NULL instead of an empty string. This is counter to how strsep itself works.

This change alters the behavior of the functions to match that of strsep.

Fixes: #565

2024-01-31 14:05 UTC, jcolp commented
cherry-pick-to: 21
cherry-pick-to: 20
cherry-pick-to: 18

2024-01-31 14:06 UTC, InterLinked1 approved these changes

2024-01-31 18:11 UTC, alex2grad reviewed
Need to change function description in include/asterisk/strings.h
  \return The next token or NULL if done or if there are more than 8 levels of
  nested quotes.

Are you sure this change won't break something else?
There are a lot of while ((token = ast_strsep...

What's about ast_strsep_quoted?
Should ast_strsep_quoted match ast_strsep behavior?

2024-01-31 18:20 UTC, jcolp commented
The ast_strsep_quoted function was also updated, which is why I used ast_strsep* to mean both occurrences to keep the length acceptable.

I've reviewed the usage of this and didn't see any cases where a problem would occur as a result of changing this, but code review exists so other people can look so I urge others to do so.

2024-01-31 18:44 UTC, seanbright approved these changes

2024-02-05 13:56 UTC, gtjoseph approved these changes

2024-02-06 14:03 UTC, gtjoseph commented
@jcolp You may have a legit test failure....
rest_api/asterisk/config/dynamic/pjsip/modify_endpoint
fails in all branches.

2024-02-06 14:04 UTC, gtjoseph requested changes
rest_api/asterisk/config/dynamic/pjsip/modify_endpoint keep failing.

2024-02-06 16:45 UTC, gtjoseph approved these changes

2024-02-06 18:55 UTC, merged