app_chanspy: Add 'D' option for dual-channel audio
asterisk/asterisk pull request #570
Opened 2024-02-01 16:47 UTC by mbradeen

Adds the 'D' option to app chanspy that causes the input and output
frames of the spied channel to be interleaved in the spy output frame.
This allows the input and output of the spied channel to be decoded
separately by the receiver.

If the 'o' option is also set, the 'D' option is ignored as the
audio being spied is inherently one direction.

Fixes: #569

UserNote: The ChanSpy application now accepts the 'D' option which
will interleave the spied audio within the outgoing frames. The
purpose of this is to allow the audio to be read as a Dual channel
stream with separate incoming and outgoing audio. Setting both the
'o' option and the 'D' option and results in the 'D' option being
ignored.

2024-02-01 16:47 UTC, mbradeen commented
cherry-pick-to: 21
cherry-pick-to: 20
cherry-pick-to: 18
cherry-pick-to: certified/18.9

2024-02-01 17:26 UTC, InterLinked1 requested changes

2024-02-01 17:26 UTC, InterLinked1 commented on apps/app_chanspy.c
> +			memcpy(read_buf, fr_read->data.ptr, sizeof(read_buf));
Why memset right before we memcpy?
Would make more sense to have:
if fr_read memcpy else memset

2024-02-01 17:26 UTC, InterLinked1 commented on apps/app_chanspy.c
> +		for (int i = 0; i < samples; i++) {
You can't declare variables in the for loop pre-condition, move `i` to the top of the block.

2024-02-02 11:48 UTC, jcolp requested changes

2024-02-02 11:48 UTC, jcolp commented on apps/app_chanspy.c
> +						the output audio as a Dual channel stream, rather than mix it. Does nothing if 'o'
dual channel

2024-02-05 13:49 UTC, jcolp approved these changes

2024-02-06 17:21 UTC, merged