Upgrade bundled pjproject to 2.14.
asterisk/asterisk pull request #577
Opened 2024-02-05 16:17 UTC by bkford

2024-02-05 16:27 UTC, bkford commented
cherry-pick-to: 21
cherry-pick-to: 20
cherry-pick-to: 18

2024-02-05 20:25 UTC, mbradeen approved these changes

2024-02-06 11:42 UTC, jcolp approved these changes

2024-02-06 12:30 UTC, silentindark approved these changes

2024-02-06 17:04 UTC, gtjoseph requested changes
How about a UserNote?

2024-02-06 20:11 UTC, merged