pseudo-MOS calculation formula change
asterisk/asterisk pull request #578
Opened 2024-02-06 13:58 UTC by romryz

The formula seems to downrate the MOS score, https://www.pingman.com/kb/article/how-is-mos-calculated-in-pingplotter-pro-50.html is the reference that seems to have been used during initial implementation. Perhaps, a typo back in time

2024-02-06 14:02 UTC, jcolp commented
Please see the code contribution instructions: https://docs.asterisk.org/Development/Policies-and-Procedures/Code-Contribution/

The contributor license agreement needs to be signed, and the commit message updated to standard.

2024-02-06 14:05 UTC, jcolp commented
As well, https://docs.asterisk.org/Deployment/Media-Experience-Score/ has links to what was used for reference information and formula details.

2024-02-06 14:14 UTC, romryz commented
@jcolp thanks, the ITU-T G.107 suggests the coefficient 7*10^(-6), which is 0.000007 (6 digits after the decimal point) vs current 7 digits after decimal point

2024-02-06 16:58 UTC, gtjoseph requested changes
A few things...   

* Add the info from the PR description to the commit message.
* Please open an issue and reference it in the commit message.
* Add a comment with the appropriate 'cherry-pick-to' lines.

See ...
https://docs.asterisk.org/Development/Policies-and-Procedures/Code-Contribution/
https://docs.asterisk.org/Development/Policies-and-Procedures/Commit-Messages/

2024-02-10 15:46 UTC, seanbright commented
The analysis and change are correct. @romryz you need to update the commit message (`git commit --amend`) and then force-push your changes (`git push --force origin patch-1`). I wouldn't worry about creating an issue.

2024-02-10 15:47 UTC, seanbright commented
cherry-pick-to: 18
cherry-pick-to: 20
cherry-pick-to: 21

2024-02-10 16:02 UTC, seanbright commented
You can refer to issue #597

2024-02-11 18:25 UTC, seanbright commented
@romryz the commit message is still not correct. I’ll provide you with one.

2024-02-11 18:33 UTC, seanbright commented
@romryz Update to use [this commit message](https://gist.github.com/seanbright/ff1fef05fe3818f4579df9d868bfe3b3). Just replace your entire commit message with that one and force-push the change again.

2024-02-11 18:39 UTC, seanbright commented
That’s not correct still. Are you using the web UI?

2024-02-11 18:43 UTC, romryz commented
no, it's the gh cli. is it the top two lines that have to be removed?

2024-02-11 18:44 UTC, romryz commented
@seanbright could you check now please, updated (again)

2024-02-11 18:44 UTC, seanbright commented
Perfect. Thank you for doing all that.

2024-02-11 18:44 UTC, seanbright approved these changes

2024-02-11 18:44 UTC, romryz commented
@seanbright thank you for supporting me on it!

2024-02-11 18:55 UTC, seanbright commented
You should be able to re-request @gtjoseph’s review

2024-02-12 16:03 UTC, gtjoseph commented
@romryz Do you happen to have an example of a "before and after" so we can see what the actual effect of changing the decimal places is on the MES?    If not, that's fine.  I'm going to test it later today anyway.

2024-02-12 16:17 UTC, jcolp approved these changes

2024-02-13 16:03 UTC, romryz commented
@gtjoseph we made some comparison on formulas to implement so I reused that template to showcase the difference - the only variable here is the T time from ITU-T, but gives an idea of how glissade looks like:
![MOS_comparison](https://github.com/asterisk/asterisk/assets/51915794/d6839500-2c0b-4538-923b-0f2244e4aa65)

2024-02-13 18:31 UTC, gtjoseph commented
> @gtjoseph we made some comparison on formulas to implement so I reused that template to showcase the difference - the only variable here is the T time from ITU-T, but gives an idea of how glissade looks like: 

Prefect, thanks!  I should be able to get this merged this afternoon or tomorrow morning.

2024-02-14 14:55 UTC, gtjoseph commented
I just tested a call between 2 local phones using ulaw both with and without the change and got an MES of 85 without the change and 88 with the change.  Those being a pseudo_mos of 4.25 and 4.4 respectively.  I thought I might have referenced "85" as the theoretical max in the documentation but I didn't so I'm good.

2024-02-14 15:05 UTC, merged