res_pjsip_session: Reset pending_media_state->read_callbacks
asterisk/asterisk pull request #612
Opened 2024-02-15 16:12 UTC by maximilianfridrich

In `handle_negotiated_sdp` the `pending_media_state->read_callbacks` must be reset before they are added in the SDP handlers in `handle_negotiated_sdp_session_media`. Otherwise, old callbacks for removed streams and file descriptors could be added to the channel and Asterisk would poll on non-existing file descriptors.

Resolves: #611

2024-02-15 16:33 UTC, maximilianfridrich commented
cherry-pick-to: 18,20,21

2024-02-15 18:05 UTC, seanbright commented
> cherry-pick-to: 18,20,21

Each needs it's own line, at least according to [the docs](https://docs.asterisk.org/Development/Policies-and-Procedures/Code-Contribution/#create-a-pull-request).

2024-02-15 19:50 UTC, gtjoseph requested changes
Each branch to be cherry-picked needs to be on its own line.

2024-02-16 07:01 UTC, maximilianfridrich commented
Oops, thank you!

2024-02-21 23:51 UTC, jcolp approved these changes

2024-02-22 04:49 UTC, jmordica commented
👀

2024-03-19 14:17 UTC, gtjoseph approved these changes

2024-03-19 14:22 UTC, gtjoseph commented
> Any progress on getting this one merged?

Sorry about that.  It was sitting in "changes requested" because the cherry-pick lines weren't there and when they were added, no one re-requested my review.

2024-03-19 20:20 UTC, merged