README.md: Removed outdated link
asterisk/asterisk pull request #618
Opened 2024-02-23 17:09 UTC by shyjuk

Removed outdated link http://www.quicknet.net from README.md

cherry-pick-to: 18
cherry-pick-to: 20
cherry-pick-to: 21

2024-02-23 22:01 UTC, mbradeen approved these changes

2024-02-23 22:04 UTC, mbradeen requested changes
Please separate the cherry-pick-to lines into a separate comment.

Generally we also require a corresponding issue to track PR's against.

2024-02-24 13:02 UTC, seanbright commented
Can we please just merge this?

2024-02-24 13:02 UTC, seanbright approved these changes

2024-02-24 18:29 UTC, merged