app_voicemail: Allow preventing mark messages as urgent.
asterisk/asterisk pull request #620
Opened 2024-02-24 20:56 UTC by InterLinked1

This adds an option to allow preventing callers from leaving messages marked as 'urgent'.

Resolves: #619

UserNote: The leaveurgent mailbox option can now be used to control whether callers may leave messages marked as 'Urgent'.

2024-02-24 20:56 UTC, InterLinked1 commented
cherry-pick-to: 18
cherry-pick-to: 20
cherry-pick-to: 21

2024-02-27 13:37 UTC, gtjoseph requested changes
The voicemail unit test now fails.

```
Result Name                           Category                  Time      
FAIL   vmuser                         /apps/app_voicemail/      <1ms
689 Test(s) Executed  688 Passed  1 Failed

[app_voicemail.c:test_voicemail_vmuser:13004]: Parse failure for leaveurgent option
```

2024-02-27 15:17 UTC, InterLinked1 commented
> The voicemail unit test now fails.
> 
> ```
> Result Name                           Category                  Time      
> FAIL   vmuser                         /apps/app_voicemail/      <1ms
> 689 Test(s) Executed  688 Passed  1 Failed
> 
> [app_voicemail.c:test_voicemail_vmuser:13004]: Parse failure for leaveurgent option
> ```

Hmm, I reviewed everything again and I'm not seeing why this could be....
This option does default to true unless most which default to false, but that seems to be right too. Any ideas on what I missed?

2024-02-27 15:53 UTC, gtjoseph commented
> > The voicemail unit test now fails.
> > ```
> > Result Name                           Category                  Time      
> > FAIL   vmuser                         /apps/app_voicemail/      <1ms
> > 689 Test(s) Executed  688 Passed  1 Failed
> > 
> > [app_voicemail.c:test_voicemail_vmuser:13004]: Parse failure for leaveurgent option
> > ```
> 
> Hmm, I reviewed everything again and I'm not seeing why this could be.... This option does default to true unless most which default to false, but that seems to be right too. Any ideas on what I missed?

Did you run the unit test yourself?

2024-02-27 16:32 UTC, gtjoseph commented
...and did you run it with the sample voicemail.conf file (which is what the unit test does)?

2024-02-29 13:33 UTC, InterLinked1 commented
> > > The voicemail unit test now fails.
> > > ```
> > > Result Name                           Category                  Time      
> > > FAIL   vmuser                         /apps/app_voicemail/      <1ms
> > > 689 Test(s) Executed  688 Passed  1 Failed
> > > 
> > > [app_voicemail.c:test_voicemail_vmuser:13004]: Parse failure for leaveurgent option
> > > ```
> > 
> > 
> > Hmm, I reviewed everything again and I'm not seeing why this could be.... This option does default to true unless most which default to false, but that seems to be right too. Any ideas on what I missed?
> 
> Did you run the unit test yourself?

Yeah, I could reproduce the failure, I just didn't understand why it was failing :)
I had tested manually previously and that had worked as expected.

Looks like it was an issue with the test string - functionality was right but my update to the test had a missing pipe.

2024-03-04 17:25 UTC, jcolp approved these changes

2024-03-05 23:35 UTC, merged