alembic: Fix compatibility with SQLAlchemy 2.0+.
asterisk/asterisk pull request #659
Opened 2024-03-20 16:30 UTC by seanbright

SQLAlchemy 2.0 changed the way that commits/rollbacks are handled causing the final `UPDATE` to our `alembic_version_<whatever>` tables to be rolled back instead of committed.

We now one connection to determine which `alembic_version_<whatever>` table to use and another to run the actual migrations. This prevents the erroneous rollback.

2024-03-20 16:30 UTC, seanbright commented
cherry-pick-to: 18
cherry-pick-to: 20
cherry-pick-to: 21

2024-03-20 18:55 UTC, mbradeen approved these changes
Tested locally

2024-03-22 09:15 UTC, jcolp requested changes
Minor error in commit message,

"We now one connection" should be "We now use one connection"

2024-03-22 12:00 UTC, jcolp approved these changes

2024-03-22 13:53 UTC, merged