apps/app_queue: Preserve reason for realtime queues
asterisk/asterisk pull request #67
Opened 2023-05-05 13:56 UTC by pnlarsson

When Asterisk is restarted it does not preserve paused reason for
members of realtime queues. This was fixed for non-realtime queues in
ASTERISK_25732

Resolves: #66

UpgradeNote: A new column needs to be added to the queue_member
table: reason_paused VARCHAR(80)

UserNote: Make paused reason in realtime queues persist an
Asterisk restart. This was fixed for non-realtime
queues in ASTERISK_25732.

2023-05-05 13:57 UTC, pnlarsson commented
cherry-pick-to: 20
cherry-pick-to: 18

2023-05-11 10:38 UTC, jcolp commented
You've put an upgrade note stating that reason_paused needs to be added, but the code makes it appear as though it is optional. Is it optional? If so then the upgrade note is not accurate.

2023-05-18 09:32 UTC, jcolp requested changes
Adding request changes to get attention on my previous comment.

2023-05-18 12:27 UTC, jcolp commented
The UpgradeNote needs to be clarified then to explain that. Right now it reads as if this is a breaking schema change.

2023-05-18 12:56 UTC, pnlarsson commented
> The UpgradeNote needs to be clarified then to explain that. Right now it reads as if this is a breaking schema change.

Changed the UpgradeNote a bit

2023-05-18 16:21 UTC, jcolp commented
The review hasn't been updated with the change.

2023-05-26 11:17 UTC, pnlarsson commented
> The review hasn't been updated with the change.

Strange I changed the top comment - is that not what is used for commit message?

2023-06-01 15:35 UTC, jcolp approved these changes

2023-06-05 18:18 UTC, gtjoseph approved these changes

2023-06-05 18:19 UTC, merged