rtp_engine: add support for multirate 2833 digits
asterisk/asterisk pull request #700
Opened 2024-04-08 17:10 UTC by mbradeen

Add 2833 DTMF support for 16K, 24K, and 32K bitrate codecs.

Asterisk currently treats rfc 2833 Digits as a single rtp payload type
with a fixed bitrate of 8K.  This change would expand that to 8, 16,
24 and 32K.

This requires checking the offered rtp types for any of these bitrates
and then adding an offer for each (if configured for 2833.)  DTMF
generation must also be changed in order to look at the current outbound
codec in order to generate appropriately timed rtp.

For cases where no outgoing audio has yet been sent prior to digit
generation, Asterisk now has a concept of a 'preferred' codec based on
offer order.

On inbound calls Asterisk will mimic the payload types of the 2833 digits.

On outbound calls Asterisk will choose the next free payload types starting
with 101.

UserNote: No change in configuration is required in order to enable this
feature. Endpoints configured to use 2833 will automatically have this
enabled. If the endpoint does not support this, it should not include it in
the SDP offer/response.

Resolves: #699

2024-04-08 17:11 UTC, mbradeen commented
cherry-pick-to: none

2024-04-08 19:04 UTC, InterLinked1 requested changes
Just saying "2833" is confusing (especially since RFC isn't even present in the commit message title), use "RFC 2833" or "RFC2833" consistently, and rfc should really be capitalized (unless referring to a case-sensitive setting or something)

2024-04-10 00:10 UTC, InterLinked1 requested changes

2024-04-10 00:10 UTC, InterLinked1 commented on main/rtp_engine.c
> +			else if (to_match->rtp_code == AST_RTP_DTMF && current->sample_rate != to_match->sample_rate) {
should be on same line as previous brace

2024-04-10 00:10 UTC, InterLinked1 commented on res/res_pjsip_sdp_rtp.c
> +	   2833 payload offers. */
RFC 2833

2024-04-10 00:10 UTC, InterLinked1 commented on res/res_pjsip_sdp_rtp.c
> +				 * Walk through the possible bitrates for the 2833/4733 digits and generate the rtpmap
RFC 2833/4733

2024-04-15 16:17 UTC, seanbright requested changes
Mostly (all?) nit-picky stuff

2024-04-15 19:47 UTC, mbradeen commented on main/rtp_engine.c
> +	set_next_mime_type(NULL, AST_RTP_DTMF, "audio", "telephone-event", 32000);
There is a tiny, tiny advantage in that the most used are generally ulaw/alaw or opus.  Not the first time this comment was made though and probably not worth the 'wrongness' in order.

2024-05-08 09:00 UTC, jcolp approved these changes

2024-05-14 13:35 UTC, merged