Fixed crush error when executing "module reload" with stasis cache registration and res_prometeus
asterisk/asterisk pull request #709
Opened 2024-04-15 08:07 UTC by codeworld0

the argument of sorcery_cache_create function must by sorcery_details* type

2024-04-15 08:48 UTC, jcolp requested changes
The commit message does not conform to standard:

https://docs.asterisk.org/Development/Policies-and-Procedures/Commit-Messages/?h=commit+messages

2024-04-15 09:14 UTC, codeworld0 commented
Corrected. Check, please

2024-04-15 09:18 UTC, jcolp commented
You only updated the PR title, the commit message itself was not updated. It should also be "crash" not "crush", and ensure that the line length does not exceed 72.

Instructions for updating a review is here:

https://docs.asterisk.org/Development/Policies-and-Procedures/Code-Contribution/#address-review-comments-and-test-failures

2024-04-15 10:03 UTC, codeworld0 commented
Corrected again. Check, please

2024-04-15 14:29 UTC, seanbright approved these changes

2024-04-22 09:25 UTC, jcolp approved these changes

2024-04-22 09:53 UTC, codeworld0 commented
cherry-pick-to: 18
cherry-pick-to: 20
cherry-pick-to: 21

2024-04-22 12:55 UTC, merged