chan_pjsip: Add multi-tenant identifier.
asterisk/asterisk pull request #741
Opened 2024-05-21 17:37 UTC by bkford

This patch introduces a new identifier on PJSIP channels: tenantid. It's
a stringfield on the channel that can be used for general purposes. It
will be inherited by other channels the same way that linkedid is.

You can set tenantid in a few ways. The first is to set it in the
dialplan with the Set(CHANNEL(tenantid)) function. It can also be
accessed in the same manner. The second way is to use setvar in
pjsip.conf on the endpoint, which brings up another change. Channel
variables will now be added to the channel on channel creation for
PJSIP. This allows us to set the tenantid (or other variables) and have
it available for things like AMI Newchannel events rather than waiting
for the channel to be created first and then have variables set later.

Fixes: #740

UserNote: tenantid has been added to PJSIP channels. It can be accessed
through dialplan via Set and CHANNEL, and can be set in pjsip.conf via
setvar.

UpgradeNote: Channel variables will now be applied to PJSIP channels on
creation rather than after. If we have tenantid set in pjsip.conf, it
will show up in Newchannel AMI events for example, whereas before it
would only be set after the Newchannel event.

2024-05-21 17:38 UTC, bkford commented
cherry-pick-to: 21
cherry-pick-to: 20
cherry-pick-to: 18

2024-05-21 21:30 UTC, alex2grad commented
> This patch introduces a new identifier on PJSIP channels: tenantid. It's a stringfield on the channel that can be used for general purposes. It will be inherited by other channels the same way that linkedid is.

As I can see this is not PJSIP channel specific, it's standard item (provided by all channel technologies).
So "new identifier on PJSIP channels" is incorrect ,

> 
> You can set tenantid in a few ways. The first is to set it in the dialplan with the Set(CHANNEL(tenantid)) function.It can also be accessed in the same manner. The second way is to use setvar in pjsip.conf on the endpoint, which brings up another change. Channel variables will now be added to the channel on channel creation for PJSIP. This allows us to set the tenantid (or other variables) and have it available for things like AMI Newchannel events rather than waiting for the channel to be created first and then have variables set later.

It's confusing description. Is it tenantid read-only or read-write?
If it's read-only then you can not use Set dialplan function.
If it's read-write then the description 
'<para>R/O returns the channel tenantid.</para>' should be changed to 
'<para>R/W the channel tenantid.</para>'
and also if it's read-write then it can be Set on ANY channels.

> 
> Fixes: #740
> 
> UserNote: tenantid has been added to PJSIP channels. It can be accessed through dialplan via Set and CHANNEL, and can be set in pjsip.conf via setvar.

Not PJSIP channels, to ANY channels.
What does it means 'can be accessed through dialplan via Set and CHANNEL'?
can be set through dialplan Set(CHANNEL(tenantid)) and can be accessed through dialplan ${CHANNEL(tenantid)}
'set_var', not 'setvar'

> 
> UpgradeNote: Channel variables will now be applied to PJSIP channels on creation rather than after. If we have tenantid set in pjsip.conf, it will show up in Newchannel AMI events for example, whereas before it would only be set after the Newchannel event.

It's confusing description.
What 'Channel variables'?  Only variables set on an PJSIP endpoint will be applied to PJSIP channels using that endpoint.
Only tenantid variable will show up in Newchannel AMI event or any PJSIP endpoint variables?

2024-06-04 17:11 UTC, bkford commented
> > This patch introduces a new identifier on PJSIP channels: tenantid. It's a stringfield on the channel that can be used for general purposes. It will be inherited by other channels the same way that linkedid is.
> 
> As I can see this is not PJSIP channel specific, it's standard item (provided by all channel technologies). So "new identifier on PJSIP channels" is incorrect ,
> 
> > You can set tenantid in a few ways. The first is to set it in the dialplan with the Set(CHANNEL(tenantid)) function.It can also be accessed in the same manner. The second way is to use setvar in pjsip.conf on the endpoint, which brings up another change. Channel variables will now be added to the channel on channel creation for PJSIP. This allows us to set the tenantid (or other variables) and have it available for things like AMI Newchannel events rather than waiting for the channel to be created first and then have variables set later.
> 
> It's confusing description. Is it tenantid read-only or read-write? If it's read-only then you can not use Set dialplan function. If it's read-write then the description 'R/O returns the channel tenantid.' should be changed to 'R/W the channel tenantid.' and also if it's read-write then it can be Set on ANY channels.
> 
> > Fixes: #740
> > UserNote: tenantid has been added to PJSIP channels. It can be accessed through dialplan via Set and CHANNEL, and can be set in pjsip.conf via setvar.
> 
> Not PJSIP channels, to ANY channels. What does it means 'can be accessed through dialplan via Set and CHANNEL'? can be set through dialplan Set(CHANNEL(tenantid)) and can be accessed through dialplan ${CHANNEL(tenantid)} 'set_var', not 'setvar'
> 
> > UpgradeNote: Channel variables will now be applied to PJSIP channels on creation rather than after. If we have tenantid set in pjsip.conf, it will show up in Newchannel AMI events for example, whereas before it would only be set after the Newchannel event.
> 
> It's confusing description. What 'Channel variables'? Only variables set on an PJSIP endpoint will be applied to PJSIP channels using that endpoint. Only tenantid variable will show up in Newchannel AMI event or any PJSIP endpoint variables?

Ack, made changes. The channel vars being set on channel creation was also creating issues, so that's been moved back to how it was before.

2024-06-10 20:51 UTC, alex2grad commented
1. Needed alembic scripts for new PJSIP endpoint option 'tenantid'

2. I think UserNote and UpgradeNote should indicate about new PJSIP endpoint option 'tenantid'

3. "The second way" - I think it's better to first describe "best approach" using  PJSIP endpoint option 'tenantid' and then note that it can also be set using set_var. The same for UserNote

2024-06-13 15:08 UTC, alex2grad commented on configs/samples/pjsip.conf.sample
> +		; Sets the tenant ID for this endpoint. Channels will have this
Needed to clarify
- what channel variable will have this value
- what can be changed via dialplan... endpoint option tenantid or channel variable tenantid.
For example:
"The channel variable tenantid will have this value  set on channel creation, and the channel variable tenantid can be changed later via dialplan."

2024-06-13 15:16 UTC, alex2grad commented on res/res_pjsip/pjsip_config.xml
> +						Sets the tenant ID for this endpoint. It will be present when
Needed to clarify
 - what channel variable will have this value
 - what can be changed via dialplan... endpoint option tenantid or channel variable tenantid.
    For example:
    "Sets the tenant ID for this endpoint. The channel variable tenantid will have this value set on channel creation, and the channel variable tenantid can be changed later through dialplan."

2024-06-13 19:50 UTC, alex2grad commented
It would be nice to be able to get CONNECTEDLINE(tenantid), like CONNECTEDLINE(tag).
It will help to get remote party tenant identifier.

2024-06-13 21:18 UTC, alex2grad commented
It would be nice to have tenantid and peer_tenantid in CDR.

2024-06-18 09:23 UTC, jcolp commented
If tag works for you for that purpose, continue to use it. I don't see tenantid as being part of CONNECTEDLINE - the same as uniqueid is not part of it, or linkedid.

2024-06-18 09:26 UTC, jcolp commented on include/asterisk/channel.h
> +	#define AST_CHANNEL_INITIALIZERS_VERSION 1
This doesn't place the value on the structure, so you can't actually do any checking or verification of the version of the underlying structured when using it. You can see an example with the CEL structure, it has a version field which gets set to it.

2024-07-17 02:21 UTC, asteriskteam commented
This PR has been marked stale because it has been in "Changes Requested" or "submitter-action-required" state for 28 days or more. Please make the requested changes within 14 days or the PR will be closed.

2024-08-06 08:59 UTC, jcolp submitted a review, later dismissed

2024-08-06 21:51 UTC, mbradeen requested changes

2024-08-06 21:51 UTC, mbradeen commented on channels/chan_pjsip.c
> +	ast_log(LOG_NOTICE, "bford: initializers.tenantid = '%s'\n", initializers.tenantid);
Logging leftover?

2024-08-06 21:51 UTC, mbradeen commented on res/res_pjsip/pjsip_config.xml
> +						the channel variable tenantid will be set to this value, and it
maybe split the second sentence into two?

> When a channel is created, the channel variable tenantid will be set to this value.  
> Can be changed via dialplan later if needed.

2024-08-07 13:11 UTC, gtjoseph requested changes
The same 3 tests consistently fail in branches 20 and 18.  They don't fail in master or 21.
The tests are in tests/channels/pjsip/basic_calls/two_parties/nominal/alice_initiated

2024-08-07 13:27 UTC, jcolp commented
I did some light digging into the artifacts, and at least in one case it was because the IPv4 UDP transport couldn't bind due to the port already being in use.

2024-08-07 19:57 UTC, gtjoseph requested changes

2024-08-07 19:57 UTC, gtjoseph commented on res/ari/ari_model_validators.c
> +		if (strcmp("tenantid", ast_json_object_iter_key(iter)) == 0) {
ari_model_validators.c and .h are generated by running `make ari_stubs` after modifying files in /rest-api/api-docs.

2024-08-08 18:47 UTC, gtjoseph approved these changes

2024-08-09 16:22 UTC, mbradeen approved these changes

2024-08-12 12:43 UTC, jcolp approved these changes

2024-08-12 15:21 UTC, merged