file.h: Rename function argument to avoid C++ keyword clash.
asterisk/asterisk pull request #749
Opened 2024-05-24 14:34 UTC by seanbright

Fixes #744

2024-05-24 14:43 UTC, jcolp requested changes
For consistency I think it should be changed in file.c as well

2024-05-24 14:59 UTC, jcolp approved these changes

2024-05-24 15:13 UTC, seanbright commented
cherry-pick-to: 21
cherry-pick-to: 20
cherry-pick-to: 18

2024-05-29 20:58 UTC, mbradeen approved these changes

2024-06-05 18:09 UTC, merged