res_stasis: fix intermittent delays on adding channel to bridge
asterisk/asterisk pull request #802
Opened 2024-07-10 19:07 UTC by mbradeen

Previously, on command execution, the control thread was awoken by
sending a SIGURG. It was found that this still resulted in some
instances where the thread was not immediately awoken.

This change instead sends a null frame to awaken the control thread,
which awakens the thread more consistently.

Resolves: #801

2024-07-10 19:08 UTC, mbradeen commented
cherry-pick-to: 18
cherry-pick-to: 20
cherry-pick-to: 21
cherry-pick-to: certified/20.7

2024-07-15 13:17 UTC, jcolp commented
@mbradeen This should go into certified 18.7 as well

2024-07-15 13:18 UTC, jcolp requested changes

2024-07-15 20:42 UTC, mbradeen commented on res/stasis/control.c
> +		/* in case the control thread is waiting on the channel, queue a null frame
changed

2024-07-17 08:51 UTC, jcolp requested changes
Looking at control_thread, do we even need it anymore? I don't think so

2024-07-31 16:34 UTC, mbradeen commented
> Looking at control_thread, do we even need it anymore? I don't think so

removed in latest

2024-08-06 08:45 UTC, jcolp approved these changes

2024-08-06 18:04 UTC, merged