Update res_agi.c， In the speech recognition module, set fr to NULL after ast_frfree(fr).
asterisk/asterisk pull request #808
Opened 2024-07-17 09:12 UTC by jiangxc

When using the speech recognition module, crashes can occurWhen using the speech recognition module, crashes can occur to a "double free or crashes can occur sporadically due to a "double free or corruption (out)" error. Now, in the section where the audio stream is being captured in a loop, each time after releasing fr, it is set to NULL to prevent repeated deallocation.

Resolves:  #772

2024-07-17 09:33 UTC, silentindark requested changes
space

2024-07-17 09:34 UTC, silentindark requested changes
space between ){

2024-07-17 09:34 UTC, silentindark commented on res/res_agi.c
> +				if (fr){
space

2024-07-17 09:35 UTC, jcolp submitted a review, later dismissed
The commit message does not conform to standard:

https://docs.asterisk.org/Development/Policies-and-Procedures/Commit-Messages/?h=commit+message

2024-07-18 12:15 UTC, jcolp commented
The commit message was not updated. You updated the Github pull request description. It also needs to be a single commit:

https://docs.asterisk.org/Development/Policies-and-Procedures/Code-Contribution/#address-review-comments-and-test-failures

You would need to squash the two commits as they exist into a single commit.

2024-08-16 01:53 UTC, asteriskteam commented
This PR has been marked stale because it has been in "Changes Requested" or "submitter-action-required" state for 28 days or more. Please make the requested changes within 14 days or the PR will be closed.

2024-08-24 00:46 UTC, jiangxc commented
Is there anything else that needs to be added?

2024-08-24 08:43 UTC, jcolp commented
The commit message does not conform to the standard and needs to be updated.

2024-09-22 02:40 UTC, asteriskteam commented
This PR has been marked stale because it has been in "Changes Requested" or "submitter-action-required" state for 28 days or more. Please make the requested changes within 14 days or the PR will be closed.

2024-09-25 16:58 UTC, silentindark approved these changes

2024-09-26 15:41 UTC, jcolp approved these changes

2024-09-30 14:52 UTC, gtjoseph commented
cherry-pick-to: 18
cherry-pick-to: 20
cherry-pick-to: 21
cherry-pick-to: 22

2024-09-30 16:23 UTC, merged