res_pjsip_sdp_rtp: Use negotiated DTMF Payload types on bitrate mismatch
asterisk/asterisk pull request #848
Opened 2024-08-21 16:13 UTC by mbradeen

When Asterisk sends an offer to Bob that includes 48K and 8K codecs with
matching 4733 offers, Bob may want to use the 48K audio codec but can not
accept 48K digits and so negotiates for a mixed set.

Asterisk will now check Bob's offer to make sure Bob has indicated this is
acceptible and if not, will use Bob's preference.

Fixes: #847

2024-08-21 16:13 UTC, mbradeen commented
cherry-pick-to: 18
cherry-pick-to: 20
cherry-pick-to: 21
cherry-pick-to: 22

testsuite-test-pr: 66

2024-08-22 14:29 UTC, gtjoseph requested changes
There was a coredump during the unit tests and the pjs4 gate test.  Both are asserts in ast_rtp_codecs_payload_code_tx_sample_rate().

You can download the artifacts from those two tests from https://github.com/asterisk/asterisk/actions/runs/10493519086?pr=848

The backtraces are in them.

2024-08-22 18:53 UTC, gtjoseph approved these changes
It's not crashing any more.  That's as much as I'll approve. :)

2024-09-03 08:53 UTC, jcolp approved these changes

2024-09-03 15:29 UTC, merged