cel_custom: Allow absolute filenames.
asterisk/asterisk pull request #893
Opened 2024-09-20 20:34 UTC by pjannesen

If a filename starts with a '/' in cel_custom [mappings] assume it is a absolute file path and not relative filename/path to AST_LOG_DIR/cel_custom/

2024-09-23 16:01 UTC, pjannesen commented
cherry-pick-to: 18
cherry-pick-to: 20
cherry-pick-to: 21
cherry-pick-to: 22

2024-09-23 21:05 UTC, seanbright commented on cel/cel_custom.c
> +			else {
This should all be on one line according to [the Coding Guidelines](https://docs.asterisk.org/Development/Policies-and-Procedures/Coding-Guidelines/#if-statements) (which is coincidentally not rendering properly on the docs site):

```
} else {
```

2024-09-25 09:50 UTC, jcolp requested changes
Marking request changes per Sean's comment.

2024-09-25 12:21 UTC, jcolp approved these changes

2024-09-25 17:02 UTC, merged