channel: Value CHANNEL(userfield) is lost by BRIDGE_ENTER/BRIDGE_LEAVE.
asterisk/asterisk pull request #894
Opened 2024-09-20 20:34 UTC by pjannesen

When a channel masquerade occurs, the value of CHANNEL(userfield) is not copied to the new ast_channel. A channel masquerade occurs when 2 existing channels are bridged using a simple bridge. Or when a simple bridge is broken and both channels continue independently.

Fixes: #882

2024-09-23 16:01 UTC, pjannesen commented
cherry-pick-to: 18
cherry-pick-to: 20
cherry-pick-to: 21
cherry-pick-to: 22

2024-09-25 09:54 UTC, jcolp requested changes
The commit message isn't accurate. A masquerade will not always occur in the circumstances given, it depends on different factors and the state of the channels. I don't think specifics like that should be in the commit message. I propose an alternative:

channel: Preserve CHANNEL(userfield) on masquerade.

In certain circumstances a channel may undergo an operation
referred to as a masquerade. If this occurs the CHANNEL(userfield)
value was not preserved causing it to get lost. This change makes
it so that this field is now preserved.

Fixes: #882

2024-09-25 12:35 UTC, pjannesen commented
I have reworded the commit and did a force push.
@jcolp thanks for de commit message!

2024-09-25 12:42 UTC, jcolp approved these changes

2024-09-25 17:03 UTC, merged