Update rtp.conf.sample
asterisk/asterisk pull request #908
Opened 2024-09-25 09:54 UTC by fabriziopicconi

stun example error

2024-09-25 13:28 UTC, seanbright commented
```
git commit --amend -m "rtp.conf.sample: Correct stunaddr example."
git push --force
```

2024-09-25 13:57 UTC, gtjoseph commented
<!--CPR-->
REMINDER: If this PR applies to other branches, please add a comment with the appropriate "cherry-pick-to" headers as per the [Create a Pull Request](https://docs.asterisk.org/Development/Policies-and-Procedures/Code-Contribution) process.  

If you don't want it cherry-picked, please add a comment with `cherry-pick-to: none` so we don't keep asking.

If, after adding "cherry-pick-to" comments, you change your mind, please edit the comment to DELETE the header lines and add `cherry-pick-to: none`.

The currently active branches are now __18, 20, 21, 22 and master__.

2024-09-25 13:58 UTC, gtjoseph requested changes
Please see seanbright's comment about the commit message and my comment about cherry-picking.

2024-09-26 06:40 UTC, fabriziopicconi commented
cherry-pick-to: none

2024-09-26 13:38 UTC, gtjoseph commented
> cherry-pick-to: none

@fabriziopicconi Why would you not want this to be cherry-picked into the other active branches?

2024-09-27 07:08 UTC, fabriziopicconi commented
> > cherry-pick-to: none
> 
> @fabriziopicconi Why would you not want this to be cherry-picked into the other active branches?

It's just a trivial documentation bug

2024-10-01 11:54 UTC, jcolp commented
It's eligible to go into all current branches.

2024-10-09 10:58 UTC, jcolp commented
I updated the branches to cherry pick into, will you be updating the commit message or should someone else do so?

2024-11-27 02:47 UTC, asteriskteam commented
This PR has been marked stale because it has been in "Changes Requested" or "submitter-action-required" state for 28 days or more. Please make the requested changes within 14 days or the PR will be closed.

2025-01-01 02:43 UTC, asteriskteam commented
This PR has been marked stale because it has been in "Changes Requested" or "submitter-action-required" state for 28 days or more. Please make the requested changes within 14 days or the PR will be closed.

2025-01-29 15:15 UTC, merged