manager.c: Restrict ModuleLoad to the configured modules directory.
asterisk/asterisk pull request #909
Opened 2024-09-25 18:19 UTC by bkford

When using the ModuleLoad AMI action, it was possible to traverse
upwards through the directories to files outside of the configured
modules directory. We decided it would be best to restrict access to
modules exclusively in the configured directory. You will now get an
error when the specified module is outside of this limitation.

Fixes: #897

UserNote: The ModuleLoad AMI action now restricts modules to the
configured modules directory.

2024-09-25 18:26 UTC, bkford commented
cherry-pick-to: 18
cherry-pick-to: 20
cherry-pick-to: 21
cherry-pick-to: 22

2024-09-26 14:42 UTC, seanbright requested changes

2024-09-26 14:42 UTC, seanbright commented on main/manager.c
> +	else if (res == -1) {
Should be on the same line

2024-09-26 14:42 UTC, seanbright commented on main/manager.c
> +	return 1;
This could just be:

    return ast_begins_with(real_path, ast_config_AST_MODULE_DIR);

2024-09-26 15:05 UTC, seanbright approved these changes

2024-09-27 08:35 UTC, jcolp approved these changes

2024-09-30 16:28 UTC, merged