res_rtp_asterisk.c: Set mark on rtp when timestamp skew is too big
asterisk/asterisk pull request #912
Opened 2024-09-25 22:52 UTC by n2p-litvinov

We faced with no audio issue when media source changed during the call (e.g. call transfer, audio prompt and then some sip endpoint, etc.). Issue related to big timestamp skew. Solution here is to set Mark when we detect such case.

2024-09-26 13:47 UTC, gtjoseph commented
@n2p-litvinov Is there an issue open for this? If not, you may want to open one. This allows the fix to be highlighted at the top of the changelog.

2024-09-26 13:48 UTC, gtjoseph requested changes
Please see the following links for proper commit message formatting:
See:
https://docs.asterisk.org/Development/Policies-and-Procedures/Code-Contribution/
https://docs.asterisk.org/Development/Policies-and-Procedures/Commit-Messages/

2024-10-02 00:05 UTC, n2p-litvinov commented
cherry-pick-to: 18
cherry-pick-to: 20
cherry-pick-to: 21
cherry-pick-to: 22

2024-10-02 00:07 UTC, n2p-litvinov commented
Thanks Joseph. 
I created an issue. Commit message was corrected. PR was updated.

2024-10-08 08:44 UTC, jcolp approved these changes

2024-11-27 02:47 UTC, asteriskteam commented
This PR has been marked stale because it has been in "Changes Requested" or "submitter-action-required" state for 28 days or more. Please make the requested changes within 14 days or the PR will be closed.

2024-11-27 13:27 UTC, n2p-litvinov commented
Hello. @gtjoseph can you please take a look?

2024-11-27 20:46 UTC, gtjoseph commented
@n2p-litvinov Oops, Sorry i missed this.  It's still in "Changes Requested" state even though it was approved so it didn't show up in my queue.  My fault.

Just FYI though...  The "Fixes" line needs to be in the PR description to trigger GitHub to auto close the issue.  If you add it to your commit later and do a force push, the PR description doesn't get updated so you have to add it there manually.  I did the fix for you.

2024-12-02 12:58 UTC, merged