main, res, tests: Fix compilation errors on FreeBSD.
asterisk/asterisk pull request #917
Opened 2024-09-29 13:26 UTC by InterLinked1

asterisk.c, manager.c: Increase buffer sizes to avoid truncation warnings.
config.c: Include header file for WIFEXITED/WEXISTSTATUS macros.
res_timing_kqueue: Use more portable format specifier.
test_crypto: Use non-linux limits.h header file.

Resolves: #916

2024-09-29 13:53 UTC, InterLinked1 commented
cherry-pick-to: 18
cherry-pick-to: 20
cherry-pick-to: 21
cherry-pick-to: 22

2024-09-29 13:54 UTC, seanbright requested changes
There is also a typo in your commit message: WEXISTSTATUS should be WEXITSTATUS.

2024-09-29 13:54 UTC, seanbright commented on res/res_timing_kqueue.c
> +		ast_test_status_update(test, "diff is %ld\n", (long) diff);
You should use `PRIu64` instead of casting.

2024-09-29 14:19 UTC, seanbright requested changes
Sorry. One more.

2024-09-29 14:19 UTC, seanbright commented on main/config.c
> +#if defined(__FreeBSD__)
I don’t _think_ this `#include` needs to be guarded by the `#if`. Both the POSIX docs and the Linux manpage specifically mention `sys/wait.h`.

2024-09-29 15:32 UTC, seanbright approved these changes

2024-10-01 11:51 UTC, jcolp approved these changes

2024-10-01 14:22 UTC, merged