app_mixmonitor: Add 'D' option for dual-channel audio.
asterisk/asterisk pull request #966
Opened 2024-10-28 19:56 UTC by bkford

Adds the 'D' option to app_mixmonitor that interleaves the input and
output frames of the channel being recorded in the monitor output frame.
This allows for two streams in the recording: the transmitted audio and
the received audio. The 't' and 'r' options are compatible with this.

Fixes: #945

UserNote: The MixMonitor application now has a new 'D' option which
interleaves the recorded audio in the output frames. This allows for
stereo recording output with one channel being the transmitted audio and
the other being the received audio. The 't' and 't' options are
compatible with this.

2024-11-01 17:58 UTC, mbradeen approved these changes

2024-11-04 09:31 UTC, jcolp requested changes

2024-11-04 09:31 UTC, jcolp commented on apps/app_mixmonitor.c
> +	MUXFLAG_AUTO_DELETE = (1 << 16),
INTERLEAVED can just be 16 and the other two not added.

2024-11-04 17:31 UTC, jcolp approved these changes

2024-11-04 18:27 UTC, bkford commented
cherry-pick-to: none

2024-11-04 20:09 UTC, merged