res_pjsip: Add new endpoint option "suppress_moh_on_remote_hold"
asterisk/asterisk pull request #981
Opened 2024-11-06 17:11 UTC by gtjoseph

Normally, when Alice calls Bob and Bob sends Asterisk a 183 Progress
response with a "sendonly" attribute in the SDP, Asterisk will start
playing MOH back to Alice.  If Bob sends early media or if you're
already playing audio to Alice (with the Dial "m" option for instance),
the MOH will replace them.  Setting "suppress_moh_on_remote_hold = yes"
on Bob's pjsip endpoint will prevent playing the MOH back to Alice
and will not interrupt the early media or playback with the Dial "m"
option.

Resolves: #979

UserNote: The new "suppress_moh_on_remote_hold" endpoint option
can be used to prevent playing MOH back to a caller if the remote
end sends "sendonly" or "inactive" (hold) to Asterisk in an SDP.

2024-11-06 17:11 UTC, gtjoseph commented
cherry-pick-to: none

2024-11-06 20:47 UTC, mbradeen approved these changes

2024-11-11 10:58 UTC, jcolp requested changes
Marking changes requested per comments on other review.

2024-11-12 15:55 UTC, jcolp submitted a review, later dismissed

2024-11-12 20:40 UTC, gtjoseph commented
just a rebase

2024-11-12 23:05 UTC, gtjoseph commented
issue with connected line fixed.

2024-11-13 15:36 UTC, jcolp approved these changes

2024-11-13 16:05 UTC, merged