func_curl.c: Add additional CURL options for SSL requests
asterisk/asterisk pull request #989
Opened 2024-11-09 19:23 UTC by mikepultz

This patch adds additional CURL TLS options / options to support mTLS authenticated requests:

* ssl_verifyhost - perform a host verification on the peer certificate (CURLOPT_SSL_VERIFYHOST)
* ssl_cainfo - define a CA certificate file (CURLOPT_CAINFO)
* ssl_capath - define a CA certificate directory (CURLOPT_CAPATH)
* ssl_cert - define a client certificate for the request (CURLOPT_SSLCERT)
* ssl_certtype - specify the client certificate type (CURLOPT_SSLCERTTYPE)
* ssl_key - define a client private key for the request (CURLOPT_SSLKEY)
* ssl_keytype - specify the client private key type (CURLOPT_SSLKEYTYPE)
* ssl_keypasswd - set a password for the private key, if required (CURLOPT_KEYPASSWD)

2024-11-09 19:24 UTC, mikepultz commented
cherry-pick-to: 21
cherry-pick-to: 22

2024-11-11 10:46 UTC, jcolp requested changes
A UserNote[1] should be added to the commit message so that the options appear in the release notes.

[1] https://docs.asterisk.org/Development/Policies-and-Procedures/Commit-Messages/?h=commit+message

2024-11-13 03:34 UTC, mikepultz commented
Hey @jcolp  - sure - just pushed the change now.

Thanks-

2024-11-14 21:06 UTC, seanbright commented
I squashed the separate commits down to one and force-pushed them.

2024-11-19 19:44 UTC, jcolp approved these changes

2024-11-20 22:43 UTC, merged