Enabling Real Time Text (RTT) for PJSIP library
asterisk/asterisk pull request #998
Opened 2024-11-18 16:07 UTC by bnandaku

Implement changes based on archived issue: https://issues-archive.asterisk.org/ASTERISK-28654

I'm the original author and I've signed CLA.

Changes are:

    chan_pjsip - added write_text function to the pjsip_tech driver
    Added case for AST_FRAME_TEXT in chan_pjsip_write_stream
    Added case to handle text in chan_pjsip_write
    pjsip/dialplan_functions.c: added logic to handle media for TEXT
    res_pjsip.h: added variables to deal with endpoint media
    channel.c: added logic to add a stream_num for a frame
    frame.c: added code to handle and fix issues with red.
    res_pjsip_sdp_rtp.c: added logic to setup SDP.
    Added logic to handle tos and cos text
    Added logic to RED for red enabled
    res_pjsip_session.c: aded logic for max_text_streams
    res_rtp_asterisk.c: Added logic to hanle Red and dealing with
    a repeating RTP issue
    pjsip_configuration.c: Added logic to handle text for PJSIP library

Original code-review can be found here:
http://lists.digium.com/pipermail/asterisk-code-review/2019-December/094886.html

2024-11-19 11:27 UTC, xBasov commented
Hi, I am Kevin Basov, I believe the commit was made under my work email: kevin.basov@cgi.com. However I am not an AUTHOR of these changes. I was the one initiating the progress of getting these RTT related modifications to the main branch.

2024-11-20 17:22 UTC, seanbright commented
There were numerous issues with this PR:

* Did not compile
* Reverted some unrelated changes (multirate DTMF)
* Code formatting

I did my best to fix all of that, but I have no way of testing these changes so I can't say if this patch actually works.

2024-11-21 20:09 UTC, seanbright requested changes
A few things I see off the bat here:

1. `red_enabled` is not being set anywhere
1. You will need [alembic migrations](https://github.com/asterisk/asterisk/tree/3dae2cf88fbe719a4f18d356cc77bb0be3fca7f5/contrib/ast-db-manage) to add `red_enabled`, `tos_text`, `cos_text`, and `max_text_streams`
1. If this were to end up in release branches then the fields added to `struct ast_sip_endpoint_media_configuration` would need to be added to the end of the struct to maintain ABI

2024-11-22 04:04 UTC, bnandaku commented
> A few things I see off the bat here:
> 
>     1. `red_enabled` is not being set anywhere
> 
>     2. You will need [alembic migrations](https://github.com/asterisk/asterisk/tree/3dae2cf88fbe719a4f18d356cc77bb0be3fca7f5/contrib/ast-db-manage) to add `red_enabled`, `tos_text`, `cos_text`, and `max_text_streams`
> 
>     3. If this were to end up in release branches then the fields added to `struct ast_sip_endpoint_media_configuration` would need to be added to the end of the struct to maintain ABI

Hey @seanbright Thank you, I'll start working on it soon.

2024-12-21 02:32 UTC, asteriskteam commented
This PR has been marked stale because it has been in "Changes Requested" or "submitter-action-required" state for 28 days or more. Please make the requested changes within 14 days or the PR will be closed.

2025-01-05 02:40 UTC, asteriskteam commented
This PR has been closed because it has been in "Changes Requested" or "submitter-action-required" state for more than 42 days.

2025-01-05 02:40 UTC, closed without merging

2025-02-06 16:30 UTC, henningw commented
Just as a note - as this PR got closed, we will have a look to this topic and do the necessary adaptions now. A new PR will be created from us.

2025-03-27 17:57 UTC, henningw commented
Tomorrow a new version will be pushed that should restore API compatibility and address also the other smaller remarks.